org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Kotlin编译器优化
kotlin.incremental=false
kotlin.incremental.android=false
kotlin.incremental.java=false
kotlin.incremental.js=false

# 避免路径问题
org.gradle.caching=false
android.enableR8.fullMode=false

# JVM参数优化
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.parallel=true
